ALTER TABLE wso
ALTER COLUMN g_n SET DATA TYPE BIGINT;

ALTER TABLE wso
ALTER COLUMN g_s SET DATA TYPE BIGINT;

ALTER TABLE wso
ALTER COLUMN R_n SET DATA TYPE BIGINT;

ALTER TABLE wso
ALTER COLUMN R_s SET DATA TYPE BIGINT;
.quit
